version: '3'
services:

  web:
    restart: always
    build: .
    container_name: guniWeb
    expose:
      - 5000
    volumes:
      - .:/app
    command: gunicorn --bind 0.0.0.0:5000 wsgi:app
    ports:
      - 5000:5000
#    depends_on:
#      - nginx
    environment:
      - PYTHONUNBUFFERED=0
    networks:
      - innernetwork

  nginx:
    container_name: Nginx
    restart: always
    build: ./nginx
    ports:
      - 80:80
      - 443:443
    links:
      - web:web
    volumes:
      - ./nginx:/etc/nginx
    depends_on:
      - web
    environment:
      - ENV=production
      - APPLICATION_URL=http://web
    networks:
      - innernetwork

  redis:
    container_name: Redis
    image: redis
#    ports:
#      - 6379:6379
    networks:
      - innernetwork

networks:
  innernetwork: