version: '3'
services:

  web:
    restart: always
    build: .
    container_name: guniWebLocal
    ports:
      - 80:80
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=0

  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    restart: always
    environment:
      PGDATA: "/var/lib/postgresql/data"
      POSTGRES_DB: "steemydata"
      POSTGRES_PASSWORD: "LX:954Dos#"
      POSTGRES_USER: "duane.dos"
    networks:
      - innernetwork

networks:
  innernetwork: