version: '3'
services:

  web:
    restart: always
    build: .
    container_name: guniWebLocal
    ports:
      - 80:80
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=0


  redis:
    container_name: Redis
    image: redis
    ports:
      - 6379:6379
    networks:
      - innernetwork

networks:
  innernetwork: